### ISSUE TITLE
运行安装报错：error in lack of groupName

### ISSUE THREAD

**Issue by pechn** [eolinker/eoLinker-API-Management-System-OS-3.X#1]
你好，在初次运行安装时报错，该如何解决？
info:error in lack of groupName
wrongFile:/www/backend_resource/RTP/Module/AutomaticallyModule.class.php
wrongLine:61

环境：
CentOS 7.2
Nginx 1.11.3
PHP 7.0.13
MySQL 5.7.20

**Comment by mouyong** [comment]
同样的错误

**Comment by eolinker** [comment]
@pechn @mouyong 
请加我们的用户讨论群：284421832，我们的客服为您看一下。

**Comment by parse-code** [comment]
同样的错误

**Comment by ljgade** [comment]
@parse-code 请加我们的用户讨论群：284421832，我们的客服为您看一下。

**Comment by eolinker** [comment]
release目录下的才是安装文件，选择一个最新的解压运行即可     ：）
如果直接打开backend_resource是后端的源码，提示缺少相应的api参数。

**Comment by TAOTAO1904** [comment]
同问，访问localhost时出现
