### ISSUE TITLE
能否提供一个 Docker 安装镜像

### ISSUE THREAD

**Issue by gumutianqi** [eolinker/eoLinker-API-Management-System-OS-3.X#2]
如题

**Comment by eolinker** [comment]
您好，我们下一个版本会提供docker镜像，预计更新时间11月30日。
感谢您的支持 @gumutianqi

**Comment by liutf** [comment]
请问今天docker镜像发了吗？

**Comment by eolinker** [comment]
@liutf 
https://hub.docker.com/r/eolinker/eolinker-api-management-system/
在docker上面已经可以pull
我们稍后会在阿里云上面做镜像加速
