### ISSUE TITLE
[LICENSE]关于授权事宜

### ISSUE THREAD

**Issue by Inori-Lover** [eolinker/eoLinker-API-Management-System-OS-3.X#3]
关于本项目的开源授权协议，究竟是怎么一个说法呢？
我在刚才安装过程中能看到`README.txt`中间有：

> 禁止“一切公开使用于商业用途”或者“以eolinker开源版本为基础而开发的二次版本”在互联网上流通。

字样。

按照我的理解这个条款跟GNU应该是冲突的，到底以哪个为理解基础呢

**Comment by MittWillson** [comment]
应该是README不能代替Lisence的

**Comment by eolinker** [comment]
授权协议已经由GPL更改为Apache 2.0，感谢支持
